# Generated by Django 4.2.11 on 2024-04-25 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_us',
            options={'verbose_name_plural': 'contact us'},
        ),
    ]
