# Generated by Django 4.2.11 on 2024-04-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='availableTime',
        ),
        migrations.AddField(
            model_name='doctor',
            name='availableTime',
            field=models.ManyToManyField(to='doctor.availabletime'),
        ),
    ]
